### ISSUE TITLE
copy step fails

### ISSUE THREAD

**Issue by horihel** [eldadru/ksniff#114]
```sh
> kubectl sniff --context mycontext -n mynamespace mypod -v
time="2021-07-06T10:24:40+02:00" level=info msg="running in verbose mode"
time="2021-07-06T10:24:40+02:00" level=debug msg="searching for tcpdump binary using lookup list: '[ C:\\Users\\user\\.krew\\store\\sniff\\v1.6.0\\static-tcpdump \\usr\\local\\bin\\static-tcpdump C:\\Users\\user\\.kube\\plugin\\sniftime="2021-07-06T10:24:40+02:00" level=debug msg="tcpdump binary found at: 'C:\\Users\\user\\.krew\\store\\sniff\\v1.6.0\\static-tcpdump'"
time="2021-07-06T10:24:40+02:00" level=info msg="using tcpdump path at: 'C:\\Users\\user\\.krew\\store\\sniff\\v1.6.0\\static-tcpdump'"
time="2021-07-06T10:24:40+02:00" level=debug msg="pod 'mypod' status: 'Running'"
time="2021-07-06T10:24:40+02:00" level=info msg="no container specified, taking first container we found in pod."
time="2021-07-06T10:24:40+02:00" level=info msg="selected container: 'mypod'"
time="2021-07-06T10:24:40+02:00" level=info msg="sniffing method: upload static tcpdump"
time="2021-07-06T10:24:40+02:00" level=info msg="sniffing on pod: 'mypod' [namespace: 'mynamespace', container: 'mypod', filter: '', interface: 'any']"
time="2021-07-06T10:24:40+02:00" level=info msg="uploading static tcpdump binary from: 'C:\\Users\\user\\.krew\\store\\sniff\\v1.6.0\\static-tcpdump' to: '/tmp/static-tcpdump'"
time="2021-07-06T10:24:40+02:00" level=info msg="uploading file: 'C:\\Users\\user\\.krew\\store\\sniff\\v1.6.0\\static-tcpdump' to '/tmp/static-tcpdump' on container: 'mypod'"
time="2021-07-06T10:24:40+02:00" level=info msg="executing command: '[/bin/sh -c ls -alt /tmp/static-tcpdump]' on container: 'mypod', pod: 'mypod', namespace: 'mynamespace'"
time="2021-07-06T10:24:40+02:00" level=error msg="failed executing command: '[/bin/sh -c ls -alt /tmp/static-tcpdump]', exitCode: '2', stdErr: 'ls: cannot access '/tmp/static-tcpdump': No such file or directory\n'" error="command terminated with exit code 2"
time="2021-07-06T10:24:40+02:00" level=error msg="failed uploading static tcpdump binary to container, please verify the remote container has tar installed" error="command terminated with exit code 2"
Error: command terminated with exit code 2
Error: exit status 1
```
(logs have been redacted (pod names, namespaces) to not leak private information)

Shelling into the pod reveals that the file has not been copied, tar exists (it's an dotnetCore asp image).

Copying manually with `kubectl cp` (and making it executable with chmod) works and "sniff" works fine if the file already exists in /tmp/static-tcpdump.

i'm running kubectl and krew on windows.

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.11", GitCommit:"c6a2f08fc4378c5381dd948d9ad9d1080e3e6b33", GitTreeState:"clean", BuildDate:"2021-05-13T17:14:18Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

any further information i could provide?

**Comment by bostrt** [comment]
Hello! This was fixed in https://github.com/eldadru/ksniff/commit/1fdbb730aced964da522036958b77228b59a3716 and will be shipped in an upcoming release.

**Comment by GNUGradyn** [comment]
I believe I am experiencing the same issue 
```
C:\WINDOWS\system32>kubectl sniff istio-ingressgateway-744bc4f55d-t529s -n istio-system
time="2022-08-29T13:12:56-06:00" level=info msg="using tcpdump path at: 'C:\\Users\\gradyn.w\\.krew\\store\\sniff\\v1.6.2\\static-tcpdump'"
time="2022-08-29T13:12:56-06:00" level=info msg="no container specified, taking first container we found in pod."
time="2022-08-29T13:12:56-06:00" level=info msg="selected container: 'istio-proxy'"
time="2022-08-29T13:12:56-06:00" level=info msg="sniffing method: upload static tcpdump"
time="2022-08-29T13:12:56-06:00" level=info msg="sniffing on pod: 'istio-ingressgateway-744bc4f55d-t529s' [namespace: 'istio-system', container: 'istio-proxy', filter: '', interface: 'any']"
time="2022-08-29T13:12:56-06:00" level=info msg="uploading static tcpdump binary from: 'C:\\Users\\gradyn.w\\.krew\\store\\sniff\\v1.6.2\\static-tcpdump' to: '/tmp/static-tcpdump'"
time="2022-08-29T13:12:56-06:00" level=info msg="uploading file: 'C:\\Users\\gradyn.w\\.krew\\store\\sniff\\v1.6.2\\static-tcpdump' to '/tmp/static-tcpdump' on container: 'istio-proxy'"
time="2022-08-29T13:12:56-06:00" level=info msg="executing command: '[/bin/sh -c test -f /tmp/static-tcpdump]' on container: 'istio-proxy', pod: 'istio-ingressgateway-744bc4f55d-t529s', namespace: 'istio-system'"
time="2022-08-29T13:12:56-06:00" level=info msg="command: '[/bin/sh -c test -f /tmp/static-tcpdump]' executing successfully exitCode: '1', stdErr :''"
time="2022-08-29T13:12:56-06:00" level=info msg="file not found on: '/tmp/static-tcpdump', starting to upload"
time="2022-08-29T13:12:57-06:00" level=info msg="tcpdump uploaded successfully"
time="2022-08-29T13:12:57-06:00" level=info msg="spawning wireshark!"
time="2022-08-29T13:12:57-06:00" level=info msg="start sniffing on remote container"
time="2022-08-29T13:12:57-06:00" level=info msg="executing command: '[/tmp/static-tcpdump -i any -U -w - ]' on container: 'istio-proxy', pod: 'istio-ingressgateway-744bc4f55d-t529s', namespace: 'istio-system'"
time="2022-08-29T13:12:57-06:00" level=error msg="failed executing command: '[/tmp/static-tcpdump -i any -U -w - ]', exitCode: '0', stdErr: ''" error="Internal error occurred: error executing command in container: failed to exec in container: failed to start exec \"e4ac01c114ccca3868410729362018a9754bbed070738163bdaebc09c21295af\": OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: \"/tmp/static-tcpdump\": stat /tmp/static-tcpdump: no such file or directory: unknown"
time="2022-08-29T13:12:57-06:00" level=error msg="failed to start remote sniffing, stopping wireshark" error="executing sniffer failed, exit code: '0'"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x14ffad]

goroutine 33 [running]:
os.(*Process).signal(0xc0003788c0, {0x12719b0, 0x1c17540})
        /home/rbost/.gvm/gos/go1.17/src/os/exec_windows.go:49 +0x4d
os.(*Process).Signal(...)
        /home/rbost/.gvm/gos/go1.17/src/os/exec.go:138
os.(*Process).kill(...)
        /home/rbost/.gvm/gos/go1.17/src/os/exec_posix.go:68
os.(*Process).Kill(...)
        /home/rbost/.gvm/gos/go1.17/src/os/exec.go:123
ksniff/pkg/cmd.(*Ksniff).Run.func2()
        /home/rbost/go/src/github.com/bostrt/ksniff/pkg/cmd/sniff.go:406 +0xd3
created by ksniff/pkg/cmd.(*Ksniff).Run
        /home/rbost/go/src/github.com/bostrt/ksniff/pkg/cmd/sniff.go:402 +0x5ff
Error: exit status 2
```

EDIT: seems to work fine on other pods, just not the ingress gateway

**Comment by GNUGradyn** [comment]
nevermind, using the -p flag solved it
