### ISSUE TITLE
Unable to run with kubectl 1.8

### ISSUE THREAD

**Issue by abhishek-jain11** [eldadru/ksniff#49]
After `make install`, kubectl stops working and gives below error
```
panic: shorthand redefinition

goroutine 1 [running]:
k8s.io/kubernetes/vendor/github.com/spf13/pflag.(*FlagSet).AddFlag(0xc4208d4b40, 0xc4208d2d20)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/pflag/flag.go:747 +0x584
k8s.io/kubernetes/vendor/github.com/spf13/pflag.(*FlagSet).VarPF(0xc4208d4b40, 0x2d959a0, 0xc4203917d0, 0xc4203916a0, 0xa, 0xc420391698, 0x1, 0xc42019bc80, 0x71, 0x335c4b0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/pflag/flag.go:706 +0x120
k8s.io/kubernetes/vendor/github.com/spf13/pflag.(*FlagSet).VarP(0xc4208d4b40, 0x2d959a0, 0xc4203917d0, 0xc4203916a0, 0xa, 0xc420391698, 0x1, 0xc42019bc80, 0x71)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/pflag/flag.go:712 +0x8e
k8s.io/kubernetes/vendor/github.com/spf13/pflag.(*FlagSet).StringVarP(0xc4208d4b40, 0xc4203917d0, 0xc4203916a0, 0xa, 0xc420391698, 0x1, 0x0, 0x0, 0xc42019bc80, 0x71)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/pflag/string.go:42 +0xab
k8s.io/kubernetes/vendor/github.com/spf13/pflag.(*FlagSet).StringP(0xc4208d4b40, 0xc4203916a0, 0xa, 0xc420391698, 0x1, 0x0, 0x0, 0xc42019bc80, 0x71, 0xc4203917b0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/pflag/string.go:67 +0xb0
k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdForPlugin(0x2daf040, 0xc42024e960, 0xc42019f680, 0x2d804e0, 0x2f1aed8, 0x2d84e20, 0xc42008a000, 0x2d84e60, 0xc42008a008, 0x2d84e60, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/plugin.go:118 +0x3db
k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdPlugin(0x2daf040, 0xc42024e960, 0x2d84e20, 0xc42008a000, 0x2d84e60, 0xc42008a008, 0x2d84e60, 0xc42008a010, 0xc420741e60)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/plugin.go:64 +0x305
k8s.io/kubernetes/pkg/kubectl/cmd.NewKubectlCommand(0x2daf040, 0xc42024e960, 0x2d84e20, 0xc42008a000, 0x2d84e60, 0xc42008a008, 0x2d84e60, 0xc42008a010, 0x202426e)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/cmd.go:379 +0x1810
k8s.io/kubernetes/cmd/kubectl/app.Run(0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/app/kubectl.go:38 +0xc7
main.main()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:26 +0x22
```

kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:39:33Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
```

**Comment by eldadru** [comment]
Hi @abhishek-jain11, kubectl plugins are not supported for version 1.8, you should use a newer version if you'd like to use plugins (1.12 is the minimum as far as I recall)
